// frontend/src/pages/Settings.svelte
<script lang="ts">
  import { ArrowLeft, LogOut, RefreshCw } from 'lucide-svelte'
  import { bike, saveBike, syncNow } from '@/stores/app'
  import { navigate } from '@/lib/router'
  import { currentUser, signOut } from '@/stores/auth'
  import type { Bike } from '@/types'

  const emptyBike: Bike = {
    name: '',
    brand: '',
    model: '',
    year: null,
    color: '',
    engine_type: 'ICE',
    plate_number: '',
    vin: '',
    current_odometer: null,
    buying_date: null,
  }

  let form = $state<Bike>(structuredClone($bike ?? emptyBike))
  let nameError = $state('')
  let saved = $state(false)

  const LAST_SYNC_KEY = 'motolog_last_sync'
  let syncing = $state(false)
  let syncError = $state('')
  let lastSyncTime = $state(Number(localStorage.getItem(LAST_SYNC_KEY) ?? 0))

  function formatSyncTime(ts: number): string {
    if (!ts) return 'Never'
    return new Date(ts).toLocaleString()
  }

  async function handleSync() {
    syncing = true
    syncError = ''
    try {
      await syncNow()
      lastSyncTime = Number(localStorage.getItem(LAST_SYNC_KEY) ?? 0)
    } catch (e) {
      syncError = e instanceof Error ? e.message : 'Sync failed'
    } finally {
      syncing = false
    }
  }

  function handleChange(field: keyof Bike, value: string) {
    if (field === 'year' || field === 'current_odometer') {
      ;(form as Record<string, unknown>)[field] = value === '' ? null : Number(value)
    } else if (field === 'buying_date') {
      ;(form as Record<string, unknown>)[field] = value === '' ? null : value
    } else {
      ;(form as Record<string, unknown>)[field] = value
    }
    if (field === 'name') nameError = ''
  }

  async function handleSave() {
    if (!form.name.trim()) {
      nameError = 'Bike name is required'
      return
    }
    await saveBike({ ...form })
    saved = true
    setTimeout(() => (saved = false), 2500)
  }

  const inputClass =
    'w-full bg-input border border-border rounded-md px-3 py-2 text-sm text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 focus:ring-offset-background'
  const labelClass = 'text-xs font-medium text-muted-foreground'
</script>

<div class="p-4 space-y-6">
  <!-- Mobile back button header -->
  <div class="sm:hidden flex items-center gap-2 -mx-1">
    <button
      onclick={() => navigate('/')}
      class="p-1.5 rounded-md text-muted-foreground hover:text-foreground transition-colors"
      aria-label="Back"
    >
      <ArrowLeft size={20} />
    </button>
    <h1 class="text-xl font-bold text-foreground">Settings</h1>
  </div>

  <!-- Desktop heading -->
  <h1 class="hidden sm:block text-xl font-bold text-foreground">Settings</h1>

  <!-- Bike information -->
  <section class="space-y-3">
    <h2 class="text-xs font-semibold text-muted-foreground uppercase tracking-wider">
      Bike Information
    </h2>
    <div class="rounded-xl bg-card border border-border p-4 space-y-3">
      <div class="space-y-1">
        <label for="bike-name" class={labelClass}>Bike name *</label>
        <input
          id="bike-name"
          value={form.name}
          oninput={e => handleChange('name', (e.target as HTMLInputElement).value)}
          placeholder="e.g. My Filano"
          class="{inputClass} {nameError ? 'border-destructive' : ''}"
        />
        {#if nameError}
          <p class="text-xs text-destructive">{nameError}</p>
        {/if}
      </div>

      <div class="grid grid-cols-2 gap-3">
        <div class="space-y-1">
          <label for="bike-brand" class={labelClass}>Brand</label>
          <input
            id="bike-brand"
            value={form.brand}
            oninput={e => handleChange('brand', (e.target as HTMLInputElement).value)}
            placeholder="e.g. Yamaha"
            class={inputClass}
          />
        </div>
        <div class="space-y-1">
          <label for="bike-model" class={labelClass}>Model</label>
          <input
            id="bike-model"
            value={form.model}
            oninput={e => handleChange('model', (e.target as HTMLInputElement).value)}
            placeholder="e.g. Grand Filano"
            class={inputClass}
          />
        </div>
      </div>

      <div class="grid grid-cols-2 gap-3">
        <div class="space-y-1">
          <label for="bike-year" class={labelClass}>Year</label>
          <input
            id="bike-year"
            type="number"
            value={form.year ?? ''}
            oninput={e => handleChange('year', (e.target as HTMLInputElement).value)}
            placeholder="e.g. 2025"
            min={1900}
            max={2100}
            class={inputClass}
          />
        </div>
        <div class="space-y-1">
          <label for="bike-color" class={labelClass}>Color</label>
          <input
            id="bike-color"
            value={form.color}
            oninput={e => handleChange('color', (e.target as HTMLInputElement).value)}
            placeholder="e.g. Pearl White"
            class={inputClass}
          />
        </div>
      </div>

      <div class="grid grid-cols-2 gap-3">
        <div class="space-y-1">
          <label for="bike-plate" class={labelClass}>License plate</label>
          <input
            id="bike-plate"
            value={form.plate_number}
            oninput={e => handleChange('plate_number', (e.target as HTMLInputElement).value)}
            placeholder="e.g. กข 1234"
            class={inputClass}
          />
        </div>
        <div class="space-y-1">
          <label for="bike-engine" class={labelClass}>Engine type</label>
          <select
            id="bike-engine"
            value={form.engine_type}
            onchange={e => handleChange('engine_type', (e.target as HTMLSelectElement).value)}
            class="w-full bg-input border border-border rounded-md px-3 py-2 text-sm text-foreground focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 focus:ring-offset-background"
          >
            <option value="ICE">ICE</option>
            <option value="EV">EV</option>
            <option value="Hybrid">Hybrid</option>
          </select>
        </div>
      </div>

      <div class="space-y-1">
        <label for="bike-vin" class={labelClass}>VIN</label>
        <input
          id="bike-vin"
          value={form.vin}
          oninput={e => handleChange('vin', (e.target as HTMLInputElement).value)}
          placeholder="e.g. ME1SG4310P0123456"
          class={inputClass}
        />
      </div>

      <div class="space-y-1">
        <label for="bike-odo" class={labelClass}>Current odometer (km)</label>
        <input
          id="bike-odo"
          type="number"
          value={form.current_odometer ?? ''}
          oninput={e => handleChange('current_odometer', (e.target as HTMLInputElement).value)}
          placeholder="e.g. 2800"
          min={0}
          class={inputClass}
        />
      </div>

      <div class="space-y-1">
        <label for="bike-buying-date" class={labelClass}>Buying date</label>
        <input
          id="bike-buying-date"
          type="date"
          value={form.buying_date ?? ''}
          onchange={e => handleChange('buying_date', (e.target as HTMLInputElement).value)}
          class={inputClass}
        />
      </div>

      <div class="flex items-center gap-3 pt-1">
        <button
          onclick={handleSave}
          class="w-full sm:w-auto px-4 py-2 text-sm font-medium bg-primary text-primary-foreground rounded-md hover:bg-primary-hover transition-colors"
        >
          Save
        </button>
        {#if saved}
          <span class="text-sm text-success">Saved successfully</span>
        {/if}
      </div>
    </div>
  </section>

  <!-- Sync -->
  <section class="space-y-3">
    <h2 class="text-xs font-semibold text-muted-foreground uppercase tracking-wider">Sync</h2>
    <div class="rounded-xl bg-card border border-border p-4 space-y-3">
      <p class="text-sm text-muted-foreground">
        Last synced: <span class="text-foreground">{formatSyncTime(lastSyncTime)}</span>
      </p>
      <div class="flex items-center gap-3">
        <button
          onclick={handleSync}
          disabled={syncing}
          class="flex items-center gap-2 px-3 py-1.5 text-sm font-medium border border-border text-muted-foreground rounded-md hover:text-foreground transition-colors disabled:opacity-50"
        >
          <RefreshCw size={14} class={syncing ? 'animate-spin' : ''} />
          {syncing ? 'Syncing…' : 'Sync now'}
        </button>
        {#if syncError}
          <span class="text-sm text-destructive">{syncError}</span>
        {/if}
      </div>
    </div>
  </section>

  <!-- Account (mobile only) -->
  <section class="sm:hidden space-y-3">
    <h2 class="text-xs font-semibold text-muted-foreground uppercase tracking-wider">Account</h2>
    <div class="rounded-xl bg-card border border-border p-4 space-y-3">
      {#if $currentUser}
        <div class="flex items-center gap-3">
          {#if $currentUser.photoURL}
            <img src={$currentUser.photoURL} alt="avatar" class="w-9 h-9 rounded-full" />
          {/if}
          <div class="min-w-0">
            {#if $currentUser.displayName}
              <p class="text-sm font-medium text-foreground truncate">{$currentUser.displayName}</p>
            {/if}
            <p class="text-xs text-muted-foreground truncate">{$currentUser.email}</p>
          </div>
        </div>
      {/if}
      <button
        onclick={signOut}
        class="flex items-center gap-2 w-full px-3 py-2 text-sm font-medium text-destructive border border-destructive/40 rounded-md hover:bg-destructive/10 transition-colors"
      >
        <LogOut size={15} />
        Sign out
      </button>
    </div>
  </section>

  <!-- Data & backup -->
  <section class="space-y-3">
    <h2 class="text-xs font-semibold text-muted-foreground uppercase tracking-wider">
      Data & Backup
    </h2>
    <div class="rounded-xl bg-card border border-border p-4 space-y-4">
      <p class="text-sm text-muted-foreground">
        All data is stored locally in your browser. Export your data periodically to keep a backup.
      </p>
      <div class="flex gap-3">
        <button
          class="px-3 py-1.5 text-sm font-medium border border-border text-muted-foreground rounded-md hover:text-foreground transition-colors"
        >
          Export data
        </button>
        <button
          class="px-3 py-1.5 text-sm font-medium border border-border text-muted-foreground rounded-md hover:text-foreground transition-colors"
        >
          Import data
        </button>
      </div>
    </div>
  </section>
</div>

// src/pages/Settings.tsx
import { useState } from 'react'
import { useApp } from '@/context/AppContext'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import type { Bike } from '@/types'

const emptyBike: Bike = {
  name: '',
  brand: '',
  model: '',
  year: null,
  color: '',
  engine_type: 'ICE',
  plate_number: '',
  vin: '',
  current_odometer: null,
}

export default function Settings() {
  const { bike, saveBike } = useApp()
  const [form, setForm] = useState<Bike>(bike ?? emptyBike)
  const [nameError, setNameError] = useState('')
  const [saved, setSaved] = useState(false)

  function handleChange(field: keyof Bike, value: string) {
    setForm(prev => ({
      ...prev,
      [field]:
        field === 'year' || field === 'current_odometer'
          ? value === ''
            ? null
            : Number(value)
          : value,
    }))
    if (field === 'name') setNameError('')
  }

  async function handleSave() {
    if (!form.name.trim()) {
      setNameError('Bike name is required')
      return
    }
    await saveBike(form)
    setSaved(true)
    setTimeout(() => setSaved(false), 2500)
  }

  return (
    <div className="p-4 space-y-6">
      <h1 className="text-xl font-bold text-foreground">Settings</h1>

      {/* Bike information */}
      <section className="space-y-3">
        <h2 className="text-xs font-semibold text-muted-foreground uppercase tracking-wider">
          Bike Information
        </h2>
        <div className="rounded-xl bg-card border border-border p-4 space-y-3">
          <div className="space-y-1">
            <Label htmlFor="bike-name">Bike name *</Label>
            <Input
              id="bike-name"
              value={form.name}
              onChange={e => handleChange('name', e.target.value)}
              placeholder="e.g. My Filano"
              className={nameError ? 'border-destructive' : ''}
            />
            {nameError && <p className="text-xs text-destructive">{nameError}</p>}
          </div>

          <div className="grid grid-cols-2 gap-3">
            <div className="space-y-1">
              <Label htmlFor="bike-brand">Brand</Label>
              <Input
                id="bike-brand"
                value={form.brand}
                onChange={e => handleChange('brand', e.target.value)}
                placeholder="e.g. Yamaha"
              />
            </div>
            <div className="space-y-1">
              <Label htmlFor="bike-model">Model</Label>
              <Input
                id="bike-model"
                value={form.model}
                onChange={e => handleChange('model', e.target.value)}
                placeholder="e.g. Grand Filano"
              />
            </div>
          </div>

          <div className="grid grid-cols-2 gap-3">
            <div className="space-y-1">
              <Label htmlFor="bike-year">Year</Label>
              <Input
                id="bike-year"
                type="number"
                value={form.year ?? ''}
                onChange={e => handleChange('year', e.target.value)}
                placeholder="e.g. 2025"
                min={1900}
                max={2100}
              />
            </div>
            <div className="space-y-1">
              <Label htmlFor="bike-color">Color</Label>
              <Input
                id="bike-color"
                value={form.color}
                onChange={e => handleChange('color', e.target.value)}
                placeholder="e.g. Pearl White"
              />
            </div>
          </div>

          <div className="grid grid-cols-2 gap-3">
            <div className="space-y-1">
              <Label htmlFor="bike-plate">License plate</Label>
              <Input
                id="bike-plate"
                value={form.plate_number}
                onChange={e => handleChange('plate_number', e.target.value)}
                placeholder="e.g. กข 1234"
              />
            </div>
            <div className="space-y-1">
              <Label>Engine type</Label>
              <Select
                value={form.engine_type}
                onValueChange={v => handleChange('engine_type', v)}
              >
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="ICE">ICE</SelectItem>
                  <SelectItem value="EV">EV</SelectItem>
                  <SelectItem value="Hybrid">Hybrid</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>

          <div className="space-y-1">
            <Label htmlFor="bike-vin">VIN</Label>
            <Input
              id="bike-vin"
              value={form.vin}
              onChange={e => handleChange('vin', e.target.value)}
              placeholder="e.g. ME1SG4310P0123456"
            />
          </div>

          <div className="space-y-1">
            <Label htmlFor="bike-odo">Current odometer (km)</Label>
            <Input
              id="bike-odo"
              type="number"
              value={form.current_odometer ?? ''}
              onChange={e => handleChange('current_odometer', e.target.value)}
              placeholder="e.g. 2800"
              min={0}
            />
          </div>

          <div className="flex items-center gap-3 pt-1">
            <Button onClick={handleSave}>Save</Button>
            {saved && <span className="text-sm text-success">Saved successfully</span>}
          </div>
        </div>
      </section>

      {/* Data & backup */}
      <section className="space-y-3">
        <h2 className="text-xs font-semibold text-muted-foreground uppercase tracking-wider">
          Data & Backup
        </h2>
        <div className="rounded-xl bg-card border border-border p-4 space-y-4">
          <p className="text-sm text-muted-foreground">
            All data is stored locally in your browser. Export your data periodically to keep a
            backup.
          </p>
          <div className="flex gap-3">
            <Button variant="outline" size="sm">
              Export data
            </Button>
            <Button variant="outline" size="sm">
              Import data
            </Button>
          </div>
        </div>
      </section>
    </div>
  )
}
