// src/App.tsx
import { Routes, Route } from 'react-router-dom'
import Layout from '@/components/Layout'
import Home from '@/pages/Home'
import Settings from '@/pages/Settings'
import { useApp } from '@/context/AppContext'

function App() {
  const { isReady } = useApp()

  if (!isReady) {
    return (
      <div className="fixed inset-0 flex items-center justify-center bg-background">
        <p className="text-muted-foreground text-sm">Loading…</p>
      </div>
    )
  }

  return (
    <Routes>
      <Route element={<Layout />}>
        <Route path="/" element={<Home />} />
        <Route path="/settings" element={<Settings />} />
      </Route>
    </Routes>
  )
}

export default App

// src/App.svelte
<script lang="ts">
  import { onMount } from 'svelte'
  import { currentPath } from '@/lib/router'
  import { initApp, isReady } from '@/stores/app'
  import Layout from '@/components/Layout.svelte'
  import Home from '@/pages/Home.svelte'
  import Settings from '@/pages/Settings.svelte'

  onMount(() => {
    initApp().catch(console.error)
  })
</script>

{#if !$isReady}
  <div class="fixed inset-0 flex items-center justify-center bg-background">
    <div class="w-8 h-8 border-2 border-primary border-t-transparent rounded-full animate-spin"></div>
  </div>
{:else}
  <Layout>
    {#if $currentPath === '/settings'}
      <Settings />
    {:else}
      <Home />
    {/if}
  </Layout>
{/if}
